local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Net = require(ReplicatedStorage.Shared.Net)

local ProfileService = require(script.Parent.ProfileService)
local WorldService = require(script.Parent.WorldService)
local ShipFactory = require(script.Parent.ShipFactory)
local ShipService = require(script.Parent.ShipService)
local CannonService = require(script.Parent.CannonService)
local MerchantService = require(script.Parent.MerchantService)
local CaptureService = require(script.Parent.CaptureService)
local BoardingService = require(script.Parent.BoardingService)
local ShopService = require(script.Parent.ShopService)
local ModeratorService = require(script.Parent.ModeratorService)
local PortControlService = require(script.Parent.PortControlService)
local GhostShipService = require(script.Parent.GhostShipService)
local RoyalNavyService = require(script.Parent.RoyalNavyService)
local KrakenService = require(script.Parent.KrakenService)
local IslandActivityService = require(script.Parent.IslandActivityService)
local GearService = require(script.Parent.GearService)
local VillagerService = require(script.Parent.VillagerService)

local remotes = Net.bootstrap()
local profiles = ProfileService.new()
local world = WorldService.new()
local shipFactory = ShipFactory.new(world)
local ships = ShipService.new(shipFactory, world, profiles, remotes)
local cannons = CannonService.new(ships, world, remotes)
local merchants = MerchantService.new(ships)
local capture = CaptureService.new(profiles, ships)
local boarding = BoardingService.new(ships, capture, world, remotes)
local shop = ShopService.new(profiles, ships, remotes)
local moderators = ModeratorService.new(ships, merchants, remotes)
local ports = PortControlService.new(ships, profiles, world, remotes)
local ghostShip = GhostShipService.new(ships, profiles, world, remotes)
local royalNavy = RoyalNavyService.new(ships, profiles, remotes)
local kraken = KrakenService.new(ships, profiles, world, remotes)
local islandActivities = IslandActivityService.new(profiles, ships, remotes)
local gear = GearService.new(profiles, remotes)
local villagers = VillagerService.new(remotes)
shop:setGearService(gear)

world:setup()
profiles:startAutosave()
ships:start()
cannons:start()
merchants:start()
boarding:start()
shop:start()
moderators:start()
ports:start()
ghostShip:start()
royalNavy:start()
kraken:start()
islandActivities:start()
gear:start()
villagers:start(gear)

remotes.ShipInput.OnServerEvent:Connect(function(player, throttle, turn)
	ships:setInput(player, throttle, turn)
end)

remotes.TargetLock.OnServerEvent:Connect(function(player, targetModel)
	ships:setTarget(player, targetModel)
end)

Players.PlayerAdded:Connect(function(player)
	local profile = profiles:load(player)
	local spawnCFrame = world:portSpawnCFrame(Vector3.zero)
	ships:spawnPlayerShip(player, profile.ships[profile.activeShipIndex], spawnCFrame)
	shop:sendState(player)
	moderators:sendState(player)
	ports:broadcast()
	gear:giveOwnedGear(player)

	player.CharacterAdded:Connect(function(character)
		local root = character:WaitForChild("HumanoidRootPart", 10)
		local ship = ships:getPlayerShip(player)
		if root and ship then
			ships:placeCharacterOnShip(player, ship)
		end
	end)
end)

Players.PlayerRemoving:Connect(function(player)
	ships:removePlayer(player)
	profiles:release(player)
end)

game:BindToClose(function()
	for _, player in ipairs(Players:GetPlayers()) do
		profiles:save(player)
	end
end)
